### ISSUE TITLE
Crash on webdash start

### ISSUE THREAD

**Issue by Ollebolle** [jadjoubran/webdash-performance-budget#4]
Hey!

I was trying to get webdash working. I followed the "get started" section on the website, which resulted in this:

```./node_modules/.bin/webdash serve
path_to_project/node_modules/webdash-performance-budget/api.js:6
            'js-size': async (req, res) => {
                             ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (path_to_project/node_modules/webdash/scripts/api.js:41:21)
    at Module._compile (module.js:571:32)
```

**Comment by jadjoubran** [comment]
Thanks @Ollebolle!
I suspect you have an older node version which doesn't support `async/await`
Can you please run `node -v` and let me know the version you have?

**Comment by Ollebolle** [comment]
Aah, ok. I have node version: `v7.4.0`

**Comment by jadjoubran** [comment]
Yep, should be solved with an update
Let me know if that works for your (or if you can't update for some reason)

**Comment by Ollebolle** [comment]
Thanks, updated to 8.1.0 and it works now! Maybe add this as a pre-requisite to the docs somewhere :)

**Comment by jadjoubran** [comment]
It turns out async/await was added in `v7.6.0`
I just added it to the docs, thanks!
